server:
  port: ${GATEWAY_PORT:8088}

spring:
  application:
    name: api-gateway
  data:
    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
#      username: ${REDIS_USERNAME:default}
#      password: ${REDIS_PASSWORD:}
      url: ${REDIS_URL:redis://localhost:6379}
      ssl:
        enabled: true
      lettuce:
        extension:
          ssl:
            enabled: true
      connect-timeout: 5000ms
      timeout: 5000ms
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service-route
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/users/**,/api/auth/**,/api/roles/**,/api/permissions/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

jwt:
  signerKey: ${JWT_SECRET}
