import sys
import os
import asyncio
import uuid
import json
from pathlib import Path

# Configure console encoding to UTF-8 to prevent charmap/UnicodeEncodeError on Windows
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

# Add backend to Python path
sys.path.append(str(Path(__file__).resolve().parent.parent / 'backend'))

# Load environment variables
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / 'backend' / '.env')

from services.file_processor import FileProcessor
from services.content_extractor import ContentExtractor
from services.slide_generator import SlideGenerator
from services.slide_text_quality import improve_slide_text_quality
from services.slide_charts import build_chart_specs_for_slides
from services.slide_tables import build_table_specs_for_slides
from services.images import build_image_paths_for_slides
from filename_utils import pptx_path_for_task
from config import LLM_MODEL, OUTPUT_DIR

async def run_test():
    task_id = str(uuid.uuid4())
    print(f"=== Starting E2E Stock Fallback Test ===")
    print(f"Task ID: {task_id}")
    print(f"LLM Model: {LLM_MODEL}")
    
    # Vietnamese history topic containing entities like "Chiến dịch Điện Biên Phủ" and "Võ Nguyên Giáp"
    raw_content = (
        "Chủ đề: Chiến dịch Điện Biên Phủ (1954)\n\n"
        "Slide 1: Tổng quan chiến dịch Điện Biên Phủ\n"
        "- Chiến dịch Điện Biên Phủ là trận quyết chiến chiến lược vĩ đại của Quân đội Nhân dân Việt Nam.\n"
        "- Diễn ra tại lòng chảo Điện Biên Phủ năm 1954.\n"
        "- Buộc Pháp đầu hàng và rút quân khỏi Đông Dương, chấn động địa cầu.\n\n"
        "Slide 2: Đại tướng Võ Nguyên Giáp\n"
        "- Đại tướng Võ Nguyên Giáp làm Tổng tư lệnh kiêm Chỉ huy trưởng chiến dịch Điện Biên Phủ.\n"
        "- Đã đưa ra quyết định lịch sử chuyển từ phương châm 'Đánh nhanh thắng nhanh' sang 'Đánh chắc tiến chắc'.\n"
        "- Quyết định này đóng vai trò then chốt xoay chuyển cục diện và mang lại thắng lợi quyết định."
    )
    
    print("\n--- Phase 1: Content Extraction & Structuring ---")
    content_extractor = ContentExtractor(model_name=LLM_MODEL)
    structured_content = await content_extractor.extract_and_structure(
        raw_content,
        target_slides_override=2,
        force_exact_slide_count=True
    )
    
    # Force exactly 2 slides
    structured_content = await content_extractor._force_slide_count_exact(structured_content, 2)
    print("Structured Content Result:")
    print(json.dumps(structured_content, indent=2, ensure_ascii=False))
    
    print("\n--- Phase 2: Slide Text Quality Improvement ---")
    structured_content = await improve_slide_text_quality(
        content_extractor,
        structured_content,
        task_id=task_id
    )
    
    print("\n--- Phase 3: Table & Chart Generation ---")
    table_specs = await build_table_specs_for_slides(
        content_extractor,
        structured_content,
        task_id=task_id
    )
    chart_specs = await build_chart_specs_for_slides(
        content_extractor,
        structured_content,
        task_id=task_id,
        table_indices=set(table_specs.keys())
    )
    print(f"Tables: {list(table_specs.keys())}, Charts: {list(chart_specs.keys())}")
    
    print("\n--- Phase 4: Image Path Generation (plan=free to test Stock Photo Fallback) ---")
    # Setting plan="free" forces only stock photo (Wikimedia / Pexels) searches.
    image_paths = await build_image_paths_for_slides(
        content_extractor,
        structured_content,
        task_id,
        chart_specs=chart_specs,
        table_specs=table_specs,
        plan="free"
    )
    
    print("\n=== Image Paths Generation Output ===")
    print(json.dumps(image_paths, indent=2, ensure_ascii=False))
    
    # Verify debug output of image search candidates and query logs
    debug_file_path = OUTPUT_DIR / "debug" / f"{task_id}_images.json"
    if debug_file_path.exists():
        print(f"\n--- Checking debug JSON file: {debug_file_path} ---")
        try:
            with open(debug_file_path, "r", encoding="utf-8") as f:
                debug_data = json.load(f)
            print("Debug information from slide images pipeline:")
            for info in debug_data:
                slide_idx = info.get("slide_index")
                print(f"\nSlide {slide_idx}:")
                # Show stock queries generated by LLM
                semantic = info.get("semantic", {})
                queries = semantic.get("stock_queries", [])
                print(f"  Attempted Queries: {queries}")
                
                # Show selected candidate details
                selected_url = info.get("image_path")
                if selected_url:
                    print(f"  Selected Image Path: {selected_url}")
                    print(f"  Selected Image Source: {info.get('external_source')}")
                    print(f"  Selected Image Query: {info.get('external_query')}")
                else:
                    print("  Selected Image: None")
                    
                # Show tried candidates details if available
                tried = info.get("tried_candidates", [])
                print(f"  Number of tried candidates: {len(tried)}")
                for idx, cand in enumerate(tried[:3]):
                    print(f"    Candidate {idx}: URL={cand.get('url')} | Type={cand.get('type')} | Score={cand.get('relevance_score')} | Fail={cand.get('severe_failure')}")
        except Exception as e:
            print(f"Error reading debug file: {e}")
    else:
        print(f"\nWarning: Debug file {debug_file_path} not found.")

    # Create presentation file
    output_path = pptx_path_for_task(OUTPUT_DIR, structured_content.get("title", ""), task_id)
    print(f"\n--- Phase 5: PowerPoint PPTX Creation ---")
    print(f"Output PPTX Path: {output_path}")
    slide_generator = SlideGenerator()
    await slide_generator.create_slide(
        structured_content,
        output_path,
        generate_images=bool(image_paths),
        image_paths=image_paths,
        chart_specs=chart_specs,
        table_specs=table_specs,
        preset="modern"
    )
    
    print(f"\n=== Test Finished. PPTX File generated: {output_path.name} ===")

if __name__ == '__main__':
    asyncio.run(run_test())
